---
title: "Exploratory Analysis"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

&nbsp;

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(wesanderson)
library(viridis)
library(plotly) 
library(patchwork)
        
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE,
                      fig.width = 8,
                      fig.asp = .6,
                      out.width = "90%")
    
```

------

# Exploring Pollution Data Set

```{r }
modified_pollution =
  read_csv("data/uspollution_us_2000_2016.csv") %>% 
  janitor::clean_names() %>%
  select(state, date_local, no2_mean, o3_mean, 
         so2_mean, co_mean) %>%
  rename(
    no2 = no2_mean,
    co = co_mean,
    o3 = o3_mean,
    so2 = so2_mean
  ) %>% 
  separate(date_local, into = c("year", "month", "day"), sep = "\\-") %>%
  select(-c("month", "day")) %>%
  group_by(year, state) %>%
  summarize(across(everything(), mean)) %>%
  mutate_if(is.numeric, ~round(., 3)) %>%
  filter(state != "Country Of Mexico") %>%
  group_by(year) %>%
  summarize(across(everything(), mean)) %>%
  select(-c(state)) %>% 
  mutate(
    year = as.numeric(year)
  )

modified_pollution %>% 
  mutate_if(is.numeric, ~round(., 3)) %>%
  rename("no2 (ppb)" = "no2", "o3 (ppm)" = "o3", "so2 (ppb)" = "so2", "co (ppm)" = "co") %>%
  knitr::kable(caption = "United States Pollutant Concentration from 2000-2016")
```


```{r}
modified_pollution %>% 
   pivot_longer(
    no2:co,
    names_to = "pollutant_type",
    values_to = "concentration"
  )  %>% 
  mutate(measurement = case_when(
    pollutant_type %in% c("no2", "so2") ~ "ppb",
    pollutant_type %in% c("co", "o3") ~ "ppm")) %>%
   group_by(pollutant_type, measurement) %>% 
   summarize(
    mean_concentration = mean(concentration),
    median_concentration = median(concentration),
    sd_concentration = sd(concentration)) %>% 
  arrange(measurement) %>%
  knitr::kable(digits = 3)
```

&nbsp;

-----

# Comparing Distributions of Pollutant Concentrations 

```{r}
ppb_plot =
  modified_pollution %>% 
  pivot_longer(
    no2:co,
    names_to = "pollutant_type",
    values_to = "concentration"
  ) %>% 
  group_by(pollutant_type) %>% 
  filter(pollutant_type %in% c("no2", "so2")) %>%
  ggplot(aes(x = pollutant_type, y = concentration)) + 
  geom_boxplot() +
  labs(
    x = "Pollutant Type",
    y = "Concentration (ppb)",) + theme_bw() 

ppm_plot =
   modified_pollution %>% 
  pivot_longer(
    no2:co,
    names_to = "pollutant_type",
    values_to = "concentration"
  ) %>% 
  group_by(pollutant_type) %>% 
  filter(pollutant_type %in% c("o3", "co")) %>%
  ggplot(aes(x = pollutant_type, y = concentration)) + 
  geom_boxplot() +
  labs(
    x = "Pollutant Type",
    y = "Concentration (ppm)",) + theme_bw()

ppb_plot + ppm_plot + plot_annotation(title = 
                                        "Distribution of Concentration Values for each Pollutant Type")
```

```{r}
ppm_point =
  modified_pollution %>% 
  pivot_longer(
    no2:co,
    names_to = "pollutant_type",
    values_to = "concentration"
  ) %>% 
  filter(pollutant_type %in% c("o3", "co")) %>%
  ggplot(aes(x = year,y = concentration, group = pollutant_type, color = pollutant_type)) +
  geom_point() +
  geom_line() +
  scale_color_viridis(discrete = TRUE) +
  theme_bw() +
  labs(
    title = "",
    x = "Year",
    y = "Pollutant Concentration(ppm)"
  ) 

ppb_point =
  modified_pollution %>% 
  pivot_longer(
    no2:co,
    names_to = "pollutant_type",
    values_to = "concentration"
  ) %>% 
  filter(pollutant_type %in% c("no2", "so2")) %>%
  ggplot(aes(x = year,y = concentration, group = pollutant_type, color = pollutant_type)) +
  geom_point() +
  geom_line() +
  scale_color_viridis(discrete = TRUE) +
  theme_bw() +
  labs(
    title = "",
    x = "Year",
    y = "Pollutant Concentration(ppb)"
  ) 

ppb_point / ppm_point + plot_annotation(title = 
                                        "Trends in Polluntant Concentration in the US from 2000-2016")
```

&nbsp;

-----

# Exploring Trends in Death From Lung Cancer

  
```{r}
read_death_time =
  read_excel("data/DeathTrend.xlsx", 
             skip = 6) %>%
  janitor::clean_names()

x = c("colorectum_female", "colorectum_male", "liver_and_intrahepatic_bile_duct_female",
      "liver_and_intrahepatic_bile_duct_male", "lung_and_bronchus_female", 
      "lung_and_bronchus_male", "ovary_female", "uterus_cervix_and_corpus_combined_female")

remove_note = function(column_name) {
  read_death_time = read_death_time %>% 
    separate(column_name, into = c(column_name, "note"), sep = "\\-") %>% 
    select(-note)}

for (i in x) {
  read_death_time = remove_note(i)} 

death_time =
  read_death_time %>%
  filter(year %in% 2000:2016) %>%
  select(-c("breast_male", "ovary_male", "prostate_female",
            "uterus_cervix_and_corpus_combined_male")) %>%
  mutate_at(vars(-("year")), as.numeric) %>%
  mutate(
   year = as.numeric(year)
  )


```
  
```{r}
death_time %>% 
  rename(
    male = lung_and_bronchus_male,
    female = lung_and_bronchus_female
  ) %>% 
  pivot_longer(
    female:male,
    names_to = "gender", 
    values_to = "death_rate"
  ) %>% 
  ggplot(aes(x = year,y = death_rate, group = gender, color = gender)) + 
  geom_point() +
  geom_line() +
  labs(
    title = "Trend in US Death rate from Lung Cancer, 2000-2016",
    x = "Year",
    y = "Lung Cancer Death Rate(per 100,000)"
  )
```

&nbsp;

------

# Exploring relationship between trend in death rate from Lung Cancer to Pollution Concentration


```{r}
merged_death_pollution =
merge(death_time, modified_pollution, by = "year") 
```

```{r}
pollutant_variables =
  merged_death_pollution %>% 
  select(no2,o3,so2,co) %>% 
  colnames() %>% 
  as.vector()
```

Create a for loop to plot Pollutant concentration vs. Lung Cancer Death Rate


```{r}
pollutant_variables =
  pollutant_variables %>% 
  as.list()


for (i in pollutant_variables) {
  plot =
  ggplot(merged_death_pollution, aes_string(i,  "lung_and_bronchus_male")) + 
  geom_point() +
  geom_smooth(method = lm, se = FALSE) +
  labs(title = "Pollutant Concentration vs. Lung Cancer Death Rate(Male)", 
       y = "Lung Cancer Death Rate(per 100,000)") +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"))
  
  print(plot)
  
}
```

```{r}
for (i in pollutant_variables) {
  plot =
  ggplot(merged_death_pollution, aes_string(i,  "lung_and_bronchus_female")) + 
  geom_point() +
  geom_smooth(method = lm, se = FALSE) +
  labs(title = "Pollutant Concentration vs. Lung Cancer Death Rate(Female)", 
       y = "Lung Cancer Death Rate(per 100,000)") +
  theme(plot.title = element_text(hjust = 0.5, face = "bold"))
  
  print(plot)
  
}
```

-----
&nbsp;

# Exploring Incidence of Lung Cancer 

```{r}
g = list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showlakes = TRUE,
  lakecolor = toRGB('white')
)

inc_state =
  read_excel("data/IncRate.xlsx", sheet = "State", 
             skip = 6) %>%
  janitor::clean_names() %>% 
  separate(
    col = breast_both_sexes_combined,
    into = c("breast_total", "female_breast_only"),
    sep = "-"
  ) %>% 
  mutate(
    breast_male = if_else(breast_male == "n/a", "0", breast_male),
    cervix_male = if_else(cervix_male == "n/a", "0", cervix_male),
    colon_excluding_rectum_both_sexes_combined = 
      if_else(colon_excluding_rectum_both_sexes_combined == "n/a", "0",
              colon_excluding_rectum_both_sexes_combined),
    colon_excluding_rectum_female = if_else(colon_excluding_rectum_female == "n/a", "0",
                                            colon_excluding_rectum_female),
    colon_excluding_rectum_male = if_else(colon_excluding_rectum_male == "n/a", "0",
                                          colon_excluding_rectum_male)) %>%
  filter(state != "Puerto Rico")

inc_state %>%
  select(state, lung_and_bronchus_both_sexes_combined) %>%
  mutate(code = state.abb[match(state, state.name)],
         lung_and_bronchus_both_sexes_combined = as.numeric(lung_and_bronchus_both_sexes_combined)) %>%
  filter(code != is.na(code)) %>%
  relocate(state, code) %>%
  plot_geo(., locationmode = 'USA-states') %>% 
  add_trace(
    z = ~lung_and_bronchus_both_sexes_combined, text = ~state, locations = ~code,
    color = ~lung_and_bronchus_both_sexes_combined, colors = 'viridis'
  ) %>% 
  colorbar(title = "Incidence Rate") %>% 
  layout(
    title = "Distribution of Lung/Bronchus Cancer Incidence Rate by State in 2013-2017",
    geo = g
  )


```

  
  


