---
title: "Data Cleaning"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(readxl)
library(patchwork)
library(plotly)

knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```



# Death Rate State Level

```{r warning = FALSE}
death_state =
  read_excel("data/DeathRate.xlsx", sheet = "State", 
             skip = 6) %>%
  janitor::clean_names() %>% 
  separate(
    col = breast_both_sexes_combined,
    into = c("breast_total", "female_breast_only"),
    sep = "-"
  ) %>% 
  select(-female_breast_only) %>%
  mutate(
    breast_male = if_else(breast_male == "n/a", "0", breast_male),
    cervix_male = if_else(cervix_male == "n/a", "0", cervix_male),
  ) %>%
  mutate_at(vars(-("state")), as.numeric) %>%
  filter(state != "Puerto Rico")
```


# Death Rate Per Cancer Type

```{r}
death_cancer =
  read_excel("data/DeathRate.xlsx", sheet = "All US", 
             skip = 6) %>%
  janitor::clean_names()  %>%
  mutate(
    male = if_else(male == "n/a", "0", male),
    female = if_else(female == "n/a", "0", female)
  ) %>%
  separate(both_sexes_combined, into = c("both_sexes_combined", "note"), sep = "\\-") %>%
  select(-note) %>%
  mutate_at(vars(-("cancer_type")), as.numeric)
```


# Incidence Rate State Level

```{r}
inc_state =
  read_excel("data/IncRate.xlsx", sheet = "State", 
             skip = 6) %>%
  janitor::clean_names() %>% 
  separate(
    col = breast_both_sexes_combined,
    into = c("breast_total", "female_breast_only"),
    sep = "-"
  ) %>% 
  mutate(
    breast_male = if_else(breast_male == "n/a", "0", breast_male),
    cervix_male = if_else(cervix_male == "n/a", "0", cervix_male),
    colon_excluding_rectum_both_sexes_combined = if_else(colon_excluding_rectum_both_sexes_combined == "n/a", "0", colon_excluding_rectum_both_sexes_combined),
    colon_excluding_rectum_female = if_else(colon_excluding_rectum_female == "n/a", "0", colon_excluding_rectum_female),
    colon_excluding_rectum_male = if_else(colon_excluding_rectum_male == "n/a", "0", colon_excluding_rectum_male),
  ) %>%
  filter(state != "Puerto Rico") %>%
  select(-c("female_breast_only", starts_with("colon"), starts_with("rectum")))
```


# Incidence Rate Per Cancer Type

```{r warning = FALSE}
inc_cancer =
  read_excel("data/IncRate.xlsx", sheet = "All US", 
             skip = 6) %>%
  janitor::clean_names() %>% 
  mutate(
    male = if_else(male == "n/a", "0", male),
    female = if_else(female == "n/a", "0", female)
  ) %>%
  separate(both_sexes_combined, into = c("both_sexes_combined", "note"), sep = "\\-") %>%
  select(-note) %>%
  mutate_at(vars(-("cancer_type")), as.numeric) %>%
  filter(cancer_type != "Colon (excluding rectum)",
         cancer_type != "Rectum")
```


# Death Trend Over Time

```{r}
read_death_time =
  read_excel("data/DeathTrend.xlsx", 
             skip = 6) %>%
  janitor::clean_names()

x = c("colorectum_female", "colorectum_male", "liver_and_intrahepatic_bile_duct_female", "liver_and_intrahepatic_bile_duct_male", "lung_and_bronchus_female", "lung_and_bronchus_male", "ovary_female", "uterus_cervix_and_corpus_combined_female")

remove_note = function(column_name) {
  read_death_time = read_death_time %>% 
    separate(column_name, into = c(column_name, "note"), sep = "\\-") %>% 
    select(-note)}

for (i in x) {
  read_death_time = remove_note(i)} 

death_time =
  read_death_time %>%
  filter(year %in% 2000:2016) %>%
  select(-c("breast_male", "ovary_male", "prostate_female","uterus_cervix_and_corpus_combined_male")) %>%
  mutate_at(vars(-("year")), as.numeric) %>%
  mutate(year = as.factor(year))
  
```


# Pollution Data Cleaned for Incidence State Data

```{r}

pollution1 = 
  read_csv("data/uspollution_us_2000_2016.csv")  
  
pollution1 = read_csv("data/uspollution_us_2000_2016.csv") %>% 
  janitor::clean_names() %>%
  select(state, date_local, no2_mean, o3_mean, 
         so2_mean, co_mean) %>%
  separate(date_local, into = c("year", "month", "day"), sep = "\\-") %>%
  select(-c("month", "day")) %>%
  group_by(year, state) %>%
  summarize(across(everything(), mean)) %>%
  filter(state != "Country Of Mexico") %>% 
  filter(
    year %in% (2013:2017)
  ) %>% 
  ungroup() %>% 
  select(state:co_mean) %>% 
  group_by(state) %>% 
  summarize(
    no2 = mean(no2_mean),
    o3 = mean(o3_mean),
    so2 = mean(so2_mean),
    co = mean(co_mean)
  ) %>%
  mutate_if(is.numeric, ~round(., 3))
```



```{r}
pollution = read_csv("data/uspollution_us_2000_2016.csv") %>% 
  janitor::clean_names() %>%
  select(state, date_local, no2_mean, o3_mean, 
         so2_mean, co_mean) %>%
  separate(date_local, into = c("year", "month", "day"), sep = "\\-") %>%
  select(-c("month", "day")) %>%
  group_by(year, state) %>%
  summarize(across(everything(), mean)) %>%
  mutate_if(is.numeric, ~round(., 3)) %>%
  filter(state != "Country Of Mexico") %>% 
  mutate(
    year = as.numeric(year)
  )

str(pollution)
```

# Merging Pollution and Incidence Data Sets

```{r}
merged_pollute_inc =
  merge(inc_state, pollution1, by = "state")
```


# Death_time and Pollution Merged
```{r warning = FALSE}
modified_pollution =
  read_csv("data/uspollution_us_2000_2016.csv") %>% 
  janitor::clean_names() %>%
  select(state, date_local, no2_mean, o3_mean, 
         so2_mean, co_mean) %>%
  separate(date_local, into = c("year", "month", "day"), sep = "\\-") %>%
  select(-c("month", "day")) %>%
  group_by(year, state) %>%
  summarize(across(everything(), mean)) %>%
  mutate_if(is.numeric, ~round(., 3)) %>%
  filter(state != "Country Of Mexico") %>%
  group_by(year) %>%
  summarize(across(everything(), mean)) %>%
  select(-c(state)) %>% 
  mutate(
    year = as.numeric(year)
  )


```


# Plots by cancer type
```{r}
inc_cancer_plot =
  inc_cancer %>%
  select(cancer_type, female, male) %>%
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "incidence"
  ) %>%
  filter(cancer_type != "All cancer types combined",
         incidence != 0) %>%
  mutate(cancer_type = fct_reorder(cancer_type, incidence)) %>%
  ggplot(aes(x = cancer_type, y = incidence, color = sex)) +
  geom_point(aes(size = 2)) + guides(size = "none") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(title = "Cancer Incidence Rate for Different Cancer Types by Sex in 2013-2017", 
       x = "Cancer Type", y = "Incidence")

death_cancer_plot =
  death_cancer %>%
  select(cancer_type, female, male) %>%
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "death"
  ) %>%
  filter(cancer_type != "All cancer types combined",
         death != 0) %>%
  mutate(cancer_type = fct_reorder(cancer_type, death)) %>%
  ggplot(aes(x = cancer_type, y = death, color = sex)) +
  geom_point(aes(size = 2)) + guides(size = "none") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(title = "Cancer Death Rate for Different Cancer Types by Sex in 2013-2017", 
       x = "Cancer Type", y = "Death")

inc_cancer_plot + death_cancer_plot
```

