---
title: "The Effect of Concentrations of Various Air Pollutants on Cancer Prevalence at the State Level over Time"
output: 
  html_document:
    toc: true
    toc_float: true


---

&nbsp;

### **Report**

&nbsp;

### Background

Current research has shown the strong associations attributing to higher incidence of certain cancers. Not only does current research provide a rationale higher cancer screening practices, but demonstrates the deterioration caused by climate change have been linked to lackadasical environmental policies. [Insert 2018 and 2020 articles].

&nbsp;

### Motivation

Given the rapid progression of climate change, we have seen widespread effects on the environment, many of which have deleterious consequences on population health, including increased burden of cancer. Prior research has shown that air pollution is associated with the increase in both incidence and mortality for certain cancers.  Thus, we want to take a closer look at trends of levels of major air pollutants, such as NO2, SO2, and 03, and compare these trends to incidence and mortality cancer data by state, with respect to time. Our motivation for this project is to more robustly investigate the aforementioned theories by further analyzing and evaluating the associations between pollutants and certain cancer types at the population level with respect to time.

&nbsp;

### Research Questions 

Some ideas for the questions, not definite

- What is the relationship between incidence rate and mortality rate of different types of cancer?
- What has been the general trend of cancer incidence, cancer mortality, and pollution levels over time?
- What is the geographical spread of cancer rates and pollution levels look like in US?
- Is there any evidence of association between cancer rates and air pollution?

&nbsp;

### Data 

#### Data Source

Our project consists of data from two main sources: 

Regarding cancer statistics, we retrieved data from [American Cancer Society Cancer Statistics Center](https://cancerstatisticscenter.cancer.org/#!/). Raw data sets were available for download in excel format. The three data sets give us information on aggregated mortality and incidence rates from 2013 to 2017, aggregated mortality and incidence rates of various cancers at the state level from 2013 to 2017, and trends of mortality related to various cancers over time from 1930 to 2018. According to the file and website, the data source is the North American Association of Central Cancer registries. 

*Cancer Data Code:*

Average annual rate per 100,000, age adjusted to the 2000 US standard population.

Incidence/Death Rate Per Cancer Type:

- `Cancer Type` : Type of cancer
- `Both sexes combined` : Combined rate for both female and male
- `Female` : Rate for female only
- `Male` : Rate for male only

Incidence/Death Rate Per State:

- `State` : US States including `All U.S. combined` as an observation

- Following columns for each cancer types:

  - `Both sexes combined`
  - `Female`
  - `Male`



The second data set is air pollution data in the United States from 2000 to 2016. The data was gathered by the EPA and measures air pollutant concentrations(in ppb/ppm) for major pollutants at the city/county level. This is an extremely large data set with over 174,000 observations.
[Brief description of the pollution data set](https://data.world/data-society/us-air-pollution-data)

We focused our analyses on the mean values of 4 major pollutants:

- **Nitrogen Dioxide (NO2)** : measured in parts per billion
- **Sulphur Dioxide (SO2)** : measured in parts per billion
- **Carbon Monoxide (CO)** : measured in parts per million
- **Ozone (O3)** : measured in parts per million

*Pollution Data Code:*

- `State Code `: The code allocated by US EPA to each state
- `County code` : The code of counties in a specific state allocated by US EPA
- `Site Num` : The site number in a specific county allocated by US EPA
- `Address`: Address of the monitoring site
- `State` : State of monitoring site
- `County` : County of monitoring site
- `City` : City of the monitoring site
- `Date Local` : Date of monitoring

- Following Columns Per Each Pollutant:

  - `Units` : The units measured for pollutant
  - `Mean` : The arithmetic mean of concentration of pollutant within a given day
  - `AQI` : The calculated air quality index of pollutant within a given day
  - `1st Max Value` : The maximum value obtained for pollutant concentration in a given day
  - `1st Max Hour` : The hour when the maximum pollutant concentration was recorded in a given day


#### Data Cleaning

The pollution data was cleaned to have year, state, and the mean values of the 4 pollutants. In order to match the time period of the pollution data, the mortality trend data was cleaned to have observations from 2000 to 2016 only.

Cancer incidence and mortality data sets were more difficult to clean for analysis as 

&nbsp;

### Exploratory Analysis

&nbsp;

### Regression Analysis

&nbsp;

### Discussion

&nbsp;

### Conclusions



